//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangSucSolution.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TRANGSUCEntities : DbContext
    {
        public TRANGSUCEntities()
            : base("name=TRANGSUCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHD_TrangSuc> CTHD_TrangSuc { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiTrangSuc> LoaiTrangSucs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PDH_TrangSuc> PDH_TrangSuc { get; set; }
        public virtual DbSet<PhieuDatHang> PhieuDatHangs { get; set; }
        public virtual DbSet<PhieuXuatHang> PhieuXuatHangs { get; set; }
        public virtual DbSet<PXH_TrangSuc> PXH_TrangSuc { get; set; }
        public virtual DbSet<TrangSuc> TrangSucs { get; set; }
    
        public virtual int SP_DELETE_HOADON(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_HOADON", iDParameter);
        }
    
        public virtual int SP_DELETE_NHANVIEN(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_NHANVIEN", iDParameter);
        }
    
        public virtual int SP_DELETE_TRANGSUC(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_TRANGSUC", iDParameter);
        }
    
        public virtual int SP_INSERT_CTHD(string iDHD, string iDTS, Nullable<int> gia, Nullable<int> soLuong)
        {
            var iDHDParameter = iDHD != null ?
                new ObjectParameter("IDHD", iDHD) :
                new ObjectParameter("IDHD", typeof(string));
    
            var iDTSParameter = iDTS != null ?
                new ObjectParameter("IDTS", iDTS) :
                new ObjectParameter("IDTS", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_CTHD", iDHDParameter, iDTSParameter, giaParameter, soLuongParameter);
        }
    
        public virtual int SP_INSERT_HD_TRANGSUC(string mahd, string mats, Nullable<int> soluong, string tents, Nullable<int> gia)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var tentsParameter = tents != null ?
                new ObjectParameter("tents", tents) :
                new ObjectParameter("tents", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_HD_TRANGSUC", mahdParameter, matsParameter, soluongParameter, tentsParameter, giaParameter);
        }
    
        public virtual int SP_INSERT_HOADON(Nullable<bool> thanhToanLuon, string nguoiLap, Nullable<int> tongTien, string hoTenKhach, string stdKhach, string diachiKhach, Nullable<int> tinhTrang)
        {
            var thanhToanLuonParameter = thanhToanLuon.HasValue ?
                new ObjectParameter("ThanhToanLuon", thanhToanLuon) :
                new ObjectParameter("ThanhToanLuon", typeof(bool));
    
            var nguoiLapParameter = nguoiLap != null ?
                new ObjectParameter("NguoiLap", nguoiLap) :
                new ObjectParameter("NguoiLap", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(int));
    
            var hoTenKhachParameter = hoTenKhach != null ?
                new ObjectParameter("HoTenKhach", hoTenKhach) :
                new ObjectParameter("HoTenKhach", typeof(string));
    
            var stdKhachParameter = stdKhach != null ?
                new ObjectParameter("stdKhach", stdKhach) :
                new ObjectParameter("stdKhach", typeof(string));
    
            var diachiKhachParameter = diachiKhach != null ?
                new ObjectParameter("DiachiKhach", diachiKhach) :
                new ObjectParameter("DiachiKhach", typeof(string));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_HOADON", thanhToanLuonParameter, nguoiLapParameter, tongTienParameter, hoTenKhachParameter, stdKhachParameter, diachiKhachParameter, tinhTrangParameter);
        }
    
        public virtual int SP_INSERT_NHANVIEN(string hoTen, string diaChi, string sdt, string cMND, Nullable<System.DateTime> ngaySinh)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_NHANVIEN", hoTenParameter, diaChiParameter, sdtParameter, cMNDParameter, ngaySinhParameter);
        }
    
        public virtual int SP_INSERT_TRANGSUC(string tenTrangSuc, string loaiTrangSuc, Nullable<int> giaCong, Nullable<double> khoiLuongTinh, Nullable<int> soHat, Nullable<int> giaHat, string hinhAnh)
        {
            var tenTrangSucParameter = tenTrangSuc != null ?
                new ObjectParameter("TenTrangSuc", tenTrangSuc) :
                new ObjectParameter("TenTrangSuc", typeof(string));
    
            var loaiTrangSucParameter = loaiTrangSuc != null ?
                new ObjectParameter("LoaiTrangSuc", loaiTrangSuc) :
                new ObjectParameter("LoaiTrangSuc", typeof(string));
    
            var giaCongParameter = giaCong.HasValue ?
                new ObjectParameter("GiaCong", giaCong) :
                new ObjectParameter("GiaCong", typeof(int));
    
            var khoiLuongTinhParameter = khoiLuongTinh.HasValue ?
                new ObjectParameter("KhoiLuongTinh", khoiLuongTinh) :
                new ObjectParameter("KhoiLuongTinh", typeof(double));
    
            var soHatParameter = soHat.HasValue ?
                new ObjectParameter("SoHat", soHat) :
                new ObjectParameter("SoHat", typeof(int));
    
            var giaHatParameter = giaHat.HasValue ?
                new ObjectParameter("GiaHat", giaHat) :
                new ObjectParameter("GiaHat", typeof(int));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_TRANGSUC", tenTrangSucParameter, loaiTrangSucParameter, giaCongParameter, khoiLuongTinhParameter, soHatParameter, giaHatParameter, hinhAnhParameter);
        }
    
        public virtual int SP_UPDATE_HOADON(Nullable<System.DateTime> ngayThanhToan, Nullable<int> tinhTrang, string iD)
        {
            var ngayThanhToanParameter = ngayThanhToan.HasValue ?
                new ObjectParameter("NgayThanhToan", ngayThanhToan) :
                new ObjectParameter("NgayThanhToan", typeof(System.DateTime));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(int));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_HOADON", ngayThanhToanParameter, tinhTrangParameter, iDParameter);
        }
    
        public virtual int SP_UPDATE_NHANVIEN(string hoTen, string diaChi, string sdt, Nullable<System.DateTime> ngaySinh, string iD)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_NHANVIEN", hoTenParameter, diaChiParameter, sdtParameter, ngaySinhParameter, iDParameter);
        }
    
        public virtual int SP_UPDATE_TRANGSUC(string iD, Nullable<int> giaCong, Nullable<int> giaHat, string hinhAnh)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var giaCongParameter = giaCong.HasValue ?
                new ObjectParameter("GiaCong", giaCong) :
                new ObjectParameter("GiaCong", typeof(int));
    
            var giaHatParameter = giaHat.HasValue ?
                new ObjectParameter("GiaHat", giaHat) :
                new ObjectParameter("GiaHat", typeof(int));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_TRANGSUC", iDParameter, giaCongParameter, giaHatParameter, hinhAnhParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
