//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangSucSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDatHang()
        {
            this.PDH_TrangSuc = new HashSet<PDH_TrangSuc>();
        }
    
        public string SoPhieu { get; set; }
        public Nullable<int> TongGiaTri { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NguoiLap { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDH_TrangSuc> PDH_TrangSuc { get; set; }
    }
}
