//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangSucSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PXH_TrangSuc
    {
        public string IDTrangSuc { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TenTrangSuc { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual PhieuXuatHang PhieuXuatHang { get; set; }
        public virtual TrangSuc TrangSuc { get; set; }
    }
}
