//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrangSucSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangSuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrangSuc()
        {
            this.CTHD_TrangSuc = new HashSet<CTHD_TrangSuc>();
            this.PhieuDatHangs = new HashSet<PhieuDatHang>();
        }
    
        public string ID { get; set; }
        public string TenTrangSuc { get; set; }
        public string LoaiTrangSuc { get; set; }
        public Nullable<int> GiaCong { get; set; }
        public Nullable<double> KhoiLuongTinh { get; set; }
        public Nullable<int> SoHat { get; set; }
        public Nullable<int> GiaHat { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD_TrangSuc> CTHD_TrangSuc { get; set; }
        public virtual LoaiTrangSuc LoaiTrangSuc1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDatHang> PhieuDatHangs { get; set; }
    }
}
